name: waterworks
description: water works - drain!!!.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  device_info_plus: ^3.2.3
  flutter_svg: ^1.0.3
  http: ^0.13.5
  dropdown_button2: ^1.4.0
  animated_bottom_navigation_bar: ^1.1.0
  responsive_framework: ^0.1.9
  fluttertoast: ^8.0.9
  page_transition: ^2.0.9
  zsdk: ^2.0.0+11
  printing: ^5.9.3
  #esc_pos_bluetooth: ^0.4.1
  #flutter_bluetooth_basic: ^0.1.7
  #zebrautility: ^0.0.40
  bluetooth_print: ^4.3.0 

  sweetalertv2: ^0.0.2
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Light.ttf

 