name: waterworks
description: water works - drain!!!.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_svg: ^1.0.3
  http: ^0.13.5
  animated_bottom_navigation_bar: ^1.1.0
  responsive_framework: ^0.1.9
  fluttertoast: ^8.0.9
  page_transition: ^2.0.9
  path_provider: ^2.0.11
  flutter_speed_dial: ^6.0.0
  screenshot: ^1.2.3
  image: ^3.0.8
  esc_pos_utils: ^1.1.0
  permission_handler: ^10.2.0
  charset_converter: ^2.1.1
  barcode: ^2.2.3
  barcode_widget: ^2.0.3
  intl: ^0.18.0
  blue_thermal_printer: ^1.2.3
  sqflite: ^2.2.4+1
  path: ^1.8.0
  provider: ^6.0.5
  percent_indicator: ^4.2.3
  dio: ^5.0.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.12
  custom_radio_grouped_button: ^2.1.2+2
  group_radio_button: ^1.3.0
  flutter_phoenix: ^1.1.0
  flutter_easyloading: ^3.0.5
  bluetooth_enable_fork: ^0.1.6
  package_info_plus: ^3.0.3
  dropdown_button2: ^2.0.0
  geolocator: ^10.1.0
  ################ printer ##############################
  #bluetooth_print: ^4.3.0
  #print_bluetooth_thermal: ^1.0.5
  #bluetooth_thermal_printer: ^0.0.6
  #blue_print_pos: ^0.0.14
  #zebrautility: ^0.0.40
  #esc_pos_bluetooth: ^0.4.1

  #esc_pos_utils_plus: ^2.0.1+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Light.ttf
