name: waterworks
description: water works - drain!!!.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_svg: ^1.0.3
  http: ^0.13.5
  dropdown_button2: ^1.4.0
  animated_bottom_navigation_bar: ^1.1.0
  diamond_bottom_bar: ^1.0.0



  responsive_framework: ^0.1.9
  fluttertoast: ^8.0.9
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Light.ttf
